DATA SEGMENT
    NUM DW 1234H,1234H
    PROD DW 2 DUP(0)
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    LEA SI,NUM
    MOV AX,[SI]
    MOV BX,[SI+2]
    MUL BX
    MOV PROD,AX;    5A90
    MOV PROD+2,DX;   014B
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START
