DATA SEGMENT
    NUM1 DW 2345H,6762H
    NUM2 DW 1111H,1111H
    DIF DW 2 DUP(0)
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    LEA SI,NUM1
    LEA DI,NUM2
    MOV AX,[SI]
    MOV BX,[DI]
    SUB AX,BX
    MOV DIF,AX
    INC SI
    INC SI
    INC DI
    INC DI
    MOV AX,[SI]
    MOV BX,[DI]
    SBB AX,BX
    MOV DIF+2,AX
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START
