DATA SEGMENT
    NUM1 DW 0FFFFH,0FFFFH
    NUM2 DW 1111H,1111H
    SUM DW 4 DUP(0)
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    MOV AX,NUM1
    ADD AX,NUM2
    MOV SUM,AX
    MOV AX,NUM1+2
    ADC AX,NUM2+2
    JNC EXIT
    MOV SUM+4,01H
    
    EXIT:MOV SUM+2,AX
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START
