DATA SEGMENT
    NUM1 DB 72H
    NUM2 DB 02H
    QUO DB 1 DUP(0)
    REM DB 1 DUP(0)
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    MOV AL,NUM1
    MOV AH,0H
    DIV NUM2
    MOV QUO,AL
    MOV REM,AH
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START
