DATA SEGMENT
    X DW 27H
    MSG1 DB 19,13,'NUM IS EVEN$'
    MSG2 DB 10,13,'NUM IS ODD$'
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    MOV AX,X
    TEST AX,01H
    JNZ EXIT
    LEA DX,MSG1
    MOV AH,09H
    JMP LAST
    EXIT:LEA DX,MSG2
    MOV AH,09H
    INT 21H
    LAST:MOV AH,4CH
    INT 21H
    CODE ENDS
END START
