DATA SEGMENT
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA

START:
    MOV AX, DATA
    MOV DS, AX

    MOV DI, 2000H    ; STARTING OFFSET
    MOV CX, 50       ; NUMBER OF LOCATIONS TO FILL
    MOV AL, 0FCH     ; CONSTANT TO STORE

FILL_LOOP:
    MOV [DI], AL     ; STORE AL INTO MEMORY AT DS:DI
    INC DI           ; MOVE TO NEXT MEMORY LOCATION
    LOOP FILL_LOOP   ; DECREMENT CX AND REPEAT IF CX ≠ 0

EXIT:
    HLT

CODE ENDS
END START
