DATA SEGMENT
    NUM DB 12H
    MSG1 DB 10,13,'THE NUMBER IS POSITIVE$'
    MSG2 DB 10,13,'THE NUMBER IS NEGATIVE$'
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    MOV AL,NUM
    ROL AL,1
    JC NEG
    
    LEA DX,MSG1
    MOV AH,09H
    INT 21H
    JMP LAST
    
    NEG:LEA DX,MSG2
    MOV AH,09H
    INT 21H
    JMP LAST
    
    LAST:MOV AH,4CH
    INT 21H
    CODE ENDS
END START
